workflows:
  ios_release:
    name: iOS Release → TestFlight
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "ASC-Sky"

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Set up code signing (fetch & apply)
        script: |
          set -euo pipefail
          keychain add-certificates
          # Fetch (or create) App Store provisioning profile & distribution cert
          app-store-connect fetch-signing-files "com.skyengineering.sky-engineering-app" --type IOS_APP_STORE --create
          echo "== Provisioning profiles installed =="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles || true
          # Apply profiles to Xcode project
          xcode-project use-profiles
          echo "== Signing settings after applying profiles =="
          xcode-project show-build-settings --workspace "ios/Runner.xcworkspace" --scheme "Runner" | egrep "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|PROVISIONING_PROFILE|CODE_SIGN_STYLE"

      - name: Build IPA for App Store (Release)
        script: xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
