workflows:
  ios_release:
    name: iOS Release → TestFlight
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "ASC-Sky"

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.skyengineering.sky-engineering-app
        TEAM_ID: NJGU3G29BR
      # keep this if your env vars are in the ios_signing group
      groups:
        - ios_signing

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Install cert & provisioning profile (dedicated keychain)
        script: |
          set -eo pipefail

          # sanity checks
          if [ -z "${IOS_DIST_CERT_P12_BASE64:-}" ] || [ -z "${IOS_PROFILE_BASE64:-}" ]; then
            echo "✗ Missing IOS_DIST_CERT_P12_BASE64 / IOS_PROFILE_BASE64"
            exit 1
          fi

          # write files
          echo "$IOS_DIST_CERT_P12_BASE64" | base64 --decode > /tmp/dist.p12
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"
          echo "$IOS_PROFILE_BASE64" | base64 --decode > "$PROFILE_DIR/appstore.mobileprovision"

          # dedicated keychain with password
          KEYCHAIN_NAME="build"
          KEYCHAIN_PASSWORD="ci_password_123"
          KEYCHAIN_PATH="$HOME/Library/Keychains/${KEYCHAIN_NAME}.keychain-db"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"

          # ❗ Import the PKCS#12 WITHOUT forcing -t cert (keeps the private key)
          if [ -n "${IOS_DIST_CERT_PASSWORD:-}" ]; then
            security import /tmp/dist.p12 -k "$KEYCHAIN_PATH" -P "$IOS_DIST_CERT_PASSWORD" -A -f pkcs12
          else
            security import /tmp/dist.p12 -k "$KEYCHAIN_PATH" -A -f pkcs12
          fi

          # allow codesign to access the key
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH" || true

          echo "== Code signing identities in our keychain =="
          security find-identity -v -p codesigning "$KEYCHAIN_PATH" || true

          # extract profile name for specifier
          PROFILE_PLIST=$(mktemp)
          security cms -D -i "$PROFILE_DIR/appstore.mobileprovision" > "$PROFILE_PLIST"
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print:Name' "$PROFILE_PLIST")
          echo "Using provisioning profile: $PROFILE_NAME"

          # archive with explicit manual signing
          ARCHIVE_PATH="$PWD/build/ios/xcarchive/Runner.xcarchive"
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            "PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID" \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            CODE_SIGN_STYLE=Manual \
            "PROVISIONING_PROFILE_SPECIFIER=$PROFILE_NAME" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            clean archive

          # export IPA
          cat > /tmp/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROFILE_NAME}</string>
            </dict>
            <key>uploadBitcode</key><false/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

          mkdir -p build/ios/ipa
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportOptionsPlist /tmp/ExportOptions.plist -exportPath build/ios/ipa

      - name: List produced IPA
        script: ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
