workflows:
  ios_release:
    name: iOS Release → TestFlight
    instance_type: mac_mini_m2

    # 👉 Use the EXACT name of your App Store Connect integration here
    integrations:
      app_store_connect: "ASC-Sky"

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Set up code signing (fetch & apply)
        script: |
          keychain add-certificates
          app-store-connect fetch-signing-files "com.skyengineering.sky-engineering-app" --type IOS_APP_STORE --create
          xcode-project use-profiles

      - name: Build IPA for App Store (Release)
        script: xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner" --archive-configuration "Release" --export-method "app-store"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
