name: sky_engineering_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.4
  pdf: ^3.11.0
  printing: ^5.13.5
  path_provider: ^2.1.4
  super_clipboard: ^0.8.3
  shared_preferences: ^2.3.2
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo_white.png
    - assets/icon-square-white.png
    - assets/logo-horizontal-white.png
    - assets/SkyEngineering-Horizontal-Light.png

flutter_native_splash:
  color: "#00426A"
  color_dark: "#00426A"

  image: assets/icon-square-white.png
  image_dark: assets/icon-square-white.png

  branding: assets/logo-horizontal-white.png
  branding_dark: assets/logo-horizontal-white.png
  branding_mode: bottom

  android_gravity: center
  ios_content_mode: center

  android: true
  ios: true
  web: false

  android_12:
    image: assets/icon-square-white.png
    icon_background_color: "#00426A"
    icon_background_color_dark: "#00426A"

